parameters:
  project:
    type: string
    default: ""
  primary_branch:
    type: string
    default: "main"
  release:
    type: boolean
    default: false
  environment:
    type: string
    default: "staging"
  primary_region:
    type: string
    default: "usw2"
  build_args:
    type: string
    default: ""
